name: Close Stale Issues

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight

jobs:
  close_stale_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Close stale issues
        uses: actions/stale@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "Closing due to inactivity. Please reopen if needed."
          days-before-stale: 7
          days-before-close: 14
